const CLEAR_LIST = "CLEAR_LIST";
const REMOVE_ITEM = "REMOVE_ITEM";
const ITEM_INCREASE = "ITEM_INCREASE";
const ITEM_DECREASE = "ITEM_DECREASE";

export { CLEAR_LIST, REMOVE_ITEM, ITEM_INCREASE, ITEM_DECREASE };
