const CLEAR_LIST = "CLEAR_LIST";
const REMOVE_ITEM = "REMOVE_ITEM";
const ITEM_INCREASE = "ITEM_INCREASE";
const ITEM_DECREASE = "ITEM_DECREASE";
const GET_TOTAL = "GET_TOTAL";
const LOADING = "LOADING";
const GET_DATA = "GET_DATA";

export {
  CLEAR_LIST,
  REMOVE_ITEM,
  ITEM_INCREASE,
  ITEM_DECREASE,
  GET_TOTAL,
  LOADING,
  GET_DATA,
};
